# fly.toml file generated for facial-analysis-webapp on 2021-02-23T17:44:38-08:00

app = "facial-analysis-webapp"

[build]
  image = "flyio/hellofly:latest"

kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "10s"
    port = "8080"
    restart_limit = 5
    timeout = "2s"
