const guide =  {"getUpload": {
    "text": "Hello there! To start, please input an image of a face. Or, read through the background information on the left!",
    "speed": 20,
    "eraseDelay": 10000000,
    "typingDelay": 0,
    "eraseSpeed": 30},
"Uploading": {"text": "Loading...this might take a while...", 
    "speed": 20,
    "eraseDelay": 1000,
    "typingDelay": 100,
    "eraseSpeed": 30},
"Uploaded": {"text": "Your results are out! Is this what you expected?", 
    "speed": 20,
    "eraseDelay": 10000000,
    "typingDelay": 100,
    "eraseSpeed": 30},
"Input": {"text": "You got us! Please input the correct information.", 
    "speed": 20,
    "eraseDelay": 10000000,
    "typingDelay": 100,
    "eraseSpeed": 30},
"Analysis": {"text": "Here is what our model focused on with respect to our predictions.", 
"speed": 20,
"eraseDelay": 10000000,
"typingDelay": 100,
"eraseSpeed": 30}};

export default {guide};